spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/organic_store
    username: root
    password: vu070504
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: organicfood.hotro@gmail.com
    password: axqdfabgiutwszbp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    from: organicfood.hotro@gmail.com
app:
  name: "Organic Food Store"  # Tên ứng dụng (hiển thị trong email)
  frontend:
    url: "http://localhost:5173"  # URL frontend để tạo link đăng nhập
  support:
    email: "organicfood.hotro@gmail.com"  # Email hỗ trợ
    phone: "0123-456-789"

lhv:
  jwt:
    base64-secret: "CiltUWryHlnBnlOhZdcn6y496q6H6xF3OQeCP0pij6SJiWgkcrAAYMv32HnYTtktDDdpGT64oDrb1zvQpN7z9A=="
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 864000

lehienvu:
  upload-file:
    base-path: "file:../upload/"
    base-uri: "../upload/"


payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "58X4B4HP"
    secretKey: "VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ"
    returnUrl: "https://active-illustrated-pound-vendors.trycloudflare.com/api/v1/payment/vn-pay-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "billpayment"
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}